# Generated by Django 5.2.7 on 2025-10-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=200, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
