# Generated by Django 5.2.6 on 2025-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_called_at_order_created_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('ONLINE', 'Электронно')], db_index=True, default='CASH', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
