# Generated by Django 5.2.7 on 2025-10-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_remove_order_latitude_remove_order_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Необработан'), ('NEW', 'Принят'), ('COOKING', 'Готовится'), ('DELIVERING', 'Доставляется'), ('COMPLETED', 'Завершён')], db_index=True, default='UNPROCESSED', max_length=20, verbose_name='Статус'),
        ),
    ]
